// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/ronaldocristover/app-monitoring/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// BackupService is an autogenerated mock type for the BackupService type
type BackupService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, req
func (_m *BackupService) Create(ctx context.Context, req *model.CreateBackupRequest) (*model.Backup, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Backup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.CreateBackupRequest) (*model.Backup, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.CreateBackupRequest) *model.Backup); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Backup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.CreateBackupRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *BackupService) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *BackupService) GetByID(ctx context.Context, id uuid.UUID) (*model.Backup, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Backup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Backup, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Backup); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Backup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByService provides a mock function with given fields: ctx, serviceID, req
func (_m *BackupService) ListByService(ctx context.Context, serviceID uuid.UUID, req *model.ListBackupsRequest) ([]*model.Backup, int64, error) {
	ret := _m.Called(ctx, serviceID, req)

	if len(ret) == 0 {
		panic("no return value specified for ListByService")
	}

	var r0 []*model.Backup
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.ListBackupsRequest) ([]*model.Backup, int64, error)); ok {
		return rf(ctx, serviceID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.ListBackupsRequest) []*model.Backup); ok {
		r0 = rf(ctx, serviceID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Backup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *model.ListBackupsRequest) int64); ok {
		r1 = rf(ctx, serviceID, req)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, *model.ListBackupsRequest) error); ok {
		r2 = rf(ctx, serviceID, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, id, req
func (_m *BackupService) Update(ctx context.Context, id uuid.UUID, req *model.UpdateBackupRequest) (*model.Backup, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Backup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.UpdateBackupRequest) (*model.Backup, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.UpdateBackupRequest) *model.Backup); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Backup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *model.UpdateBackupRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBackupService creates a new instance of BackupService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBackupService(t interface {
	mock.TestingT
	Cleanup(func())
}) *BackupService {
	mock := &BackupService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
