// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/ronaldocristover/app-monitoring/internal/service"
	mock "github.com/stretchr/testify/mock"
)

// DashboardService is an autogenerated mock type for the DashboardService type
type DashboardService struct {
	mock.Mock
}

// GetDashboardStats provides a mock function with given fields: ctx
func (_m *DashboardService) GetDashboardStats(ctx context.Context) (*service.DashboardStats, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDashboardStats")
	}

	var r0 *service.DashboardStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*service.DashboardStats, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *service.DashboardStats); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.DashboardStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDashboardService creates a new instance of DashboardService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDashboardService(t interface {
	mock.TestingT
	Cleanup(func())
}) *DashboardService {
	mock := &DashboardService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
