// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/ronaldocristover/app-monitoring/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MonitoringLogService is an autogenerated mock type for the MonitoringLogService type
type MonitoringLogService struct {
	mock.Mock
}

// GetLatest provides a mock function with given fields: ctx, serviceID
func (_m *MonitoringLogService) GetLatest(ctx context.Context, serviceID uuid.UUID) (*model.MonitoringLog, error) {
	ret := _m.Called(ctx, serviceID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatest")
	}

	var r0 *model.MonitoringLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.MonitoringLog, error)); ok {
		return rf(ctx, serviceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.MonitoringLog); ok {
		r0 = rf(ctx, serviceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MonitoringLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, serviceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByService provides a mock function with given fields: ctx, serviceID, req
func (_m *MonitoringLogService) ListByService(ctx context.Context, serviceID uuid.UUID, req *model.ListMonitoringLogsRequest) ([]*model.MonitoringLog, int64, error) {
	ret := _m.Called(ctx, serviceID, req)

	if len(ret) == 0 {
		panic("no return value specified for ListByService")
	}

	var r0 []*model.MonitoringLog
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.ListMonitoringLogsRequest) ([]*model.MonitoringLog, int64, error)); ok {
		return rf(ctx, serviceID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.ListMonitoringLogsRequest) []*model.MonitoringLog); ok {
		r0 = rf(ctx, serviceID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.MonitoringLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *model.ListMonitoringLogsRequest) int64); ok {
		r1 = rf(ctx, serviceID, req)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, *model.ListMonitoringLogsRequest) error); ok {
		r2 = rf(ctx, serviceID, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewMonitoringLogService creates a new instance of MonitoringLogService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMonitoringLogService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MonitoringLogService {
	mock := &MonitoringLogService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
