// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/ronaldocristover/app-monitoring/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MonitoringConfigService is an autogenerated mock type for the MonitoringConfigService type
type MonitoringConfigService struct {
	mock.Mock
}

// GetByService provides a mock function with given fields: ctx, serviceID
func (_m *MonitoringConfigService) GetByService(ctx context.Context, serviceID uuid.UUID) (*model.MonitoringConfig, error) {
	ret := _m.Called(ctx, serviceID)

	if len(ret) == 0 {
		panic("no return value specified for GetByService")
	}

	var r0 *model.MonitoringConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.MonitoringConfig, error)); ok {
		return rf(ctx, serviceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.MonitoringConfig); ok {
		r0 = rf(ctx, serviceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MonitoringConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, serviceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: ctx, serviceID, req
func (_m *MonitoringConfigService) Upsert(ctx context.Context, serviceID uuid.UUID, req *model.UpdateMonitoringConfigRequest) (*model.MonitoringConfig, error) {
	ret := _m.Called(ctx, serviceID, req)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 *model.MonitoringConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.UpdateMonitoringConfigRequest) (*model.MonitoringConfig, error)); ok {
		return rf(ctx, serviceID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.UpdateMonitoringConfigRequest) *model.MonitoringConfig); ok {
		r0 = rf(ctx, serviceID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MonitoringConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *model.UpdateMonitoringConfigRequest) error); ok {
		r1 = rf(ctx, serviceID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMonitoringConfigService creates a new instance of MonitoringConfigService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMonitoringConfigService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MonitoringConfigService {
	mock := &MonitoringConfigService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
