version: "2"
with-expecter: true
mockname: "Mock{{.InterfaceName}}"
filename: "{{.InterfaceName}}.go"
outpkg: "handler"
dir: "{{.InterfaceDir}}/../handler/mocks"
packages:
  github.com/ronaldocristover/app-monitoring/internal/service:
    interfaces:
      AuthService:
      UserService:
      AppService:
      EnvironmentService:
      ServerService:
      ServiceService:
      MonitoringConfigService:
      MonitoringLogService:
      DeploymentService:
      BackupService:
      DashboardService:
